### ISSUE TITLE
Twain/sane scanner driver

### ISSUE THREAD

**Issue by cvinh** [pywebdriver/pywebdriver#148]
Hello
Can anyone confirm we could connect a twain scanner in order to attach images to a pos order or to a customer in pos ?
Thanks in advance

**Comment by legalsylvain** [comment]
never saw such functionnality.

**Comment by cvinh** [comment]
> never saw such functionnality.
yes but do you think it's feasible ?

**Comment by cvinh** [comment]
@sebastienbeau would you help here ? we can sponsor
