### ISSUE TITLE
OCA ?

### ISSUE THREAD

**Issue by PierrickBrun** [pywebdriver/pywebdriver#57]
Opening this issue to discuss the possible integration of pywebdriver in the OCA.

The goal is to answer these questions:
 - Is it relevant ?
 - What would it require for it to be included ?

**Comment by dreispt** [comment]
From what I’ve read on your mailing list announcement, I don’t see why not. Is there a sources repo you can point to?

**Comment by alexis-via** [comment]
Yes, it is relevant to propose it to OCA.
I don't know what it would require to include it...
In the short term, I think the 1st priority would be to have a POS that works well on v14 with pywebdriver. Credit card is starting to work (still needs improvement). With your great work, printer now works. We still have to work on LCD.

**Comment by PierrickBrun** [comment]
Hi @dreispt 
You can find the main project here: 
https://github.com/akretion/pywebdriver

But there is also those linked repositories that may need to follow pywebdriver in the OCA:
https://github.com/akretion/py-xml-escpos
https://github.com/akretion/pypostelium
https://github.com/akretion/pyposdisplay



Also, bout what's been said in the mailing list, we will need to:
 - improve the CI
 - extend the README and explain the pros and cons of using pywebdriver.

This is something I will work on

**Comment by JuanDCG** [comment]
@OCA/iot-maintainers
@diggy128

Since this great project is related to replace IoT Box that should be at PSC IoT ???

**Comment by diggy128** [comment]
From my point of view, I certainly see it fit.
But since it is about modules that don't install on odoo itself, maybe we need yet another IOT repo to keep assistive modules like those separate?

**Comment by JuanDCG** [comment]
For me, IoT as concept, is more like a Framework of technologies HW/SW/Protocols/Data...

Generally IoT with 1 repo is nonadministrative and ideally. It should be split in many folders. 

I'll change the PSC's name to IoT Framework, maybe as a vertical too.

And inside the umbrella of PSC IoT Framework, could be many repositories.

There are many boards...many OS & languages...many actuators/sensors...many protocols...security... From the point of view of Things.( like "frontend" ).

Form the point of view of "backend" on cloud there are also complex architectures to manage all the data and analyze it.

**Comment by JuanDCG** [comment]
A good picture for IoT is like this:

![image](https://user-images.githubusercontent.com/60073506/103173759-78c0ed00-485d-11eb-9b6e-7971a36683aa.png)

**Comment by JuanDCG** [comment]
So, at this discussion, the Flask pywebdriver should be like REST API enpoints architectures.

And Odoo IoT framework instead Thinger.io server....

**Comment by PierrickBrun** [comment]
I think this could be easier to have pywebdriver separated from the rest of the IoT, maybe when pywebdriver is more aligned with the OCA guidelines


Also, I've worked on the CI so I think this is a first step

**Comment by legalsylvain** [comment]
hello all.

Discussed recently with @PierrickBrun and @sebastienbeau (all from akretion).

- The main maintainer of this project @PierrickBrun, will leave akretion in some weeks and will probably stop working on odoo + pywebdriver
- At this step, pywebdriver is not a classic "OCA" project (not odoo modules, not the same CI, specific buid to create windows and debian packages)
- Contrary to what has been said on this thread, it is not related to OCA/iot project

As a result, the three of us think it's best and the more simple to keep this project out of the OCA for the time being. However, we think it's better to use a new organization for better visibility and to be more cross company.

- we created a new organization, named "pywebdriver"
- we renamed the project https://github.com/akretion/pywebdriver into https://github.com/pywebdriver/pywebdriver

**Comment by patehgaye** [comment]
Hi Everyone I am facing difficulties integrating Pywebdriver  with Odoo, I have already installed both Odoo 16 and Pywebdriver but I can print reports from Odoo to the printer directly without downloading the files. If anyone here can help I will be very grateful for that.
